site_name: Moving Rainbow
pages:
- [README.md, Welcome]
- [guide/hardware.md, Hardware]
- [guide/bill-of-materials.md, Bill of Materials]
- [src/lab-01/index.md, Lab 1 - Blink!]
- [src/lab-02/index.md, Lab 2]
theme: readthedocs